### ISSUE TITLE
help: 这工具还有效吗？输入id 一直不行

### ISSUE THREAD

**Issue by zhuhang-jasper** [qinlili23333/ctfileGet#10]
这工具还有效吗？输入id 一直不行

下载地址：
https://u062.com/file/650393-241893419
ctfile://xturlAmEEbgdmBTBXMgE-BmldMAdmVmNSbwMqUCUGYQ1qWmlWY1YyUzlWZAR2UCNVPlwzVzQGN1JmBzsFMlIxDWUANgI2

**Comment by qinlili23333** [comment]
链接格式是旧格式，你需要重新生成新格式的分享链接
