### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by taiwan-king** [qinlili23333/ctfileGet#12]
![1651287179188](https://user-images.githubusercontent.com/24381898/166087763-c8e88150-e790-477a-9e1f-1e9d4beab49e.jpg)

如果要通用碼的話再麻煩大大提供,
感謝

**Comment by qinlili23333** [comment]
文件ID格式错误

**Comment by taiwan-king** [comment]
![02](https://user-images.githubusercontent.com/24381898/166095502-ab5eadd1-f27e-4dda-b168-65157261da0a.jpg)
您好,
我用舊的版面貼網址也是無法使用,
如果新的版面ID格式錯誤,
以我這張圖片應該如何填寫,
感謝您

**Comment by qinlili23333** [comment]
新格式的分享一定有密码，只是可以开启特定域名下跳过密码，但是解析器不能跳过密码
另外文件id是最后那一长串，不是只有一小段的

**Comment by taiwan-king** [comment]
感謝您

我自己耍白癡,
原來是要用自己網盤分享
功能正常,
謝謝大大辛苦開發
