### ISSUE TITLE
速度还是30kb,是不是设置出错了？

### ISSUE THREAD

**Issue by aizaimosaou** [qinlili23333/ctfileGet#17]
用的idm下载的
  
直链链接如下

https://ch1-cucc-dd.tv002.com/down/ad5f1781e15e5f7cd567ad00e3257e9e/Chrome%20v102.0.5005.115%20x64%20Green.7z?cts=wt-f-D61A53A131A253Ff5722&ctp=61A53A131A253&ctt=1655846131&limit=1&spd=30000&ctk=ad5f1781e15e5f7cd567ad00e3257e9e&chk=a0f9de32e6685dbf35eb836aa924d19b-79032753

是不是idm哪设置的有问题？
代理为netdisk;11.22
线程是4个

**Comment by qinlili23333** [comment]
没有出错，你解析的链接就应该是这个速度
