### ISSUE TITLE
请问还有在维护这个项止吗？

### ISSUE THREAD

**Issue by wuyusite** [qinlili23333/ctfileGet#19]
我测试几个分享，都提示无法获取。
http://ct.xde8.com/f/31834334-647651147-f67c1a
比如上面这个

**Comment by qinlili23333** [comment]
你没有输入密码
非我本人创建的分享，都必须手动输入密码，内置密码仅适用于我创建的分享

**Comment by wuyusite** [comment]
> 你没有输入密码 非我本人创建的分享，都必须手动输入密码，内置密码仅适用于我创建的分享

哦，那就是并不对外开放使用是吗？如果是的话，麻烦结帖吧，打扰了^_^

**Comment by qinlili23333** [comment]
不是不对外开放，而是外部链接需要手动输入密码

**Comment by wuyusite** [comment]
明白了，可没有密码的分享该如操作呢？我使用的是您提供的这个https://ctfile.qinlili.bid/，只填入了地址，密码留空，或许是这样才出现问题的？

**Comment by qinlili23333** [comment]
> 明白了，可没有密码的分享该如操作呢？我使用的是您提供的这个[https://ctfile.qinlili.bid/，只填入了地址，密码留空，或许是这样才出现问题的？](https://ctfile.qinlili.bid/%EF%BC%8C%E5%8F%AA%E5%A1%AB%E5%85%A5%E4%BA%86%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%AF%86%E7%A0%81%E7%95%99%E7%A9%BA%EF%BC%8C%E6%88%96%E8%AE%B8%E6%98%AF%E8%BF%99%E6%A0%B7%E6%89%8D%E5%87%BA%E7%8E%B0%E9%97%AE%E9%A2%98%E7%9A%84%EF%BC%9F)

每个分享实际上都存在密码，只是可能会不显示密码，但解析地址必须要密码，你可以问分享者获取密码
