### ISSUE TITLE
大佬，不能用了，有时间麻烦看下吧

### ISSUE THREAD

**Issue by anranaiya** [qinlili23333/ctfileGet#22]
大佬，不能用了，有时间麻烦看下吧

**Comment by qinlili23333** [comment]
提供地址

**Comment by xiaoji235** [comment]
要登陆才能下载了，没办法直接获取链接了

**Comment by ZZGithub429** [comment]
用idm下载只有几十kb

**Comment by qinlili23333** [comment]
> 用idm下载只有几十kb

不同文件，不同时间解析出来的速度都是不一样的，不能保证高速，只能保证能直接下载

**Comment by qinlili23333** [comment]
> 要登陆才能下载了，没办法直接获取链接了

目前只观测到部分文件有这个限制，至少我自己分享的文件目前仍然可以直接下载

**Comment by iPixelOldC** [comment]
> > 要登陆才能下载了，没办法直接获取链接了
> 
> 目前只观测到部分文件有这个限制，至少我自己分享的文件目前仍然可以直接下载

感觉这个像是分享者设置的一样，像这个[站](https://www.mobinovels.com/)的小说链接，感觉基本都有这个限制，v2的网页能解析出文件名和大小，但立刻会消失报错undefined。

**Comment by qinlili23333** [comment]
> > > 要登陆才能下载了，没办法直接获取链接了
> > 
> > 
> > 目前只观测到部分文件有这个限制，至少我自己分享的文件目前仍然可以直接下载
> 
> 感觉这个像是分享者设置的一样，像这个[站](https://www.mobinovels.com/)的小说链接，感觉基本都有这个限制，v2的网页能解析出文件名和大小，但立刻会消失报错undefined。 （不过话说这个是不是自己搭建解析，然后改下代码解析时带上自己的登录cookies就能解决？:P）

对，只要带上cookies就能解决，不过受限于网页沙箱问题，目前解析器无法直接实现此功能
我过几天会尝试性更新一个可以自己填写Token的功能

**Comment by qinlili23333** [comment]
已推送登录后高速解析功能，版本号2.2.0
首次打开自动生成Token，点击Token右侧登录按钮即可绑定登录
