### ISSUE TITLE
解析失败，谢谢作者

### ISSUE THREAD

**Issue by hyrulegangster** [qinlili23333/ctfileGet#24]
分享链接没有密码如下：https://d.shipengliang.com/f/22330634-653058573-24c6bf
下载源码打开button.html，或者使用在线网址登陆后解析都失败
请见截图
![Snipaste_2022-12-04_17-54-51](https://user-images.githubusercontent.com/78515915/205484706-1034c5fe-d8bf-45cb-a855-0d6abc95042a.jpg)
![Snipaste_2022-12-04_17-56-15](https://user-images.githubusercontent.com/78515915/205484714-9a24752f-ead7-4963-b09f-9e50b2b2415b.jpg)

**Comment by qinlili23333** [comment]
该链接实际上有密码，你需要输入密码

**Comment by qinlili23333** [comment]
仅在特定域名下没有密码，但实际有密码的情况下仍然需要密码来解析

**Comment by hyrulegangster** [comment]
明白了，谢谢您
