### ISSUE TITLE
複製連結後顯示需要登陸

### ISSUE THREAD

**Issue by Re1ncarnation** [qinlili23333/ctfileGet#25]
![0](https://user-images.githubusercontent.com/96719418/214834669-04986857-2bf2-4ea2-89c7-48791c17dc9a.jpg)
![1](https://user-images.githubusercontent.com/96719418/214834686-6d1987ca-c76e-47a5-acec-dd239df5ed08.jpg)

如圖，不知道哪裡可以登入...

**Comment by qinlili23333** [comment]
token右侧按钮是登录

**Comment by Humwq** [comment]
![图片](https://user-images.githubusercontent.com/9313456/227727704-bd96c86a-dc01-45ff-afbb-ac17816e2fd1.png)
仍然提示需要登陆

**Comment by Humwq** [comment]
点了本地解析  闪现了一下结果 还没加载出来就隐藏了。。。。看不到结果啊。。

**Comment by qinlili23333** [comment]
你登陆的账号不是会员账号

**Comment by BoBppy** [comment]
> 你登陆的账号不是会员账号

只有会员可以解析吗

**Comment by qinlili23333** [comment]
> > 你登陆的账号不是会员账号
> 
> 只有会员可以解析吗

需要登陆的情况下只能使用会员账号
