### ISSUE TITLE
请问怎么获取城通文件ID啊？

### ISSUE THREAD

**Issue by JcBai** [qinlili23333/ctfileGet#26]
我的诚同链接里没有那些数字，这个id要如何获取啊？能麻烦告知吗？感激不尽
我找到一个连接，把最后的数字输入之后显示下载不可用，估计这个不是文件id，能不能请您教一下如何获取文件id
<img width="800" alt="屏幕快照 2023-04-07 下午6 28 32" src="https://user-images.githubusercontent.com/64192241/230593577-51a3de66-df68-410e-976d-482cc46576d0.png">

**Comment by qinlili23333** [comment]
就是最后一串数字

**Comment by JcBai** [comment]
填入最后一串数字后，一直都是下载不可用，是为什么呢

**Comment by qinlili23333** [comment]
> 填入最后一串数字后，一直都是下载不可用，是为什么呢

你没输入文件密码

**Comment by JcBai** [comment]
感谢感谢，确实输入密码就可以了，网站自动复制的，没注意还有密码
