### ISSUE TITLE
请问一下the shared link is not filly opened的原因是什么呢

### ISSUE THREAD

**Issue by sdw81219** [qinlili23333/ctfileGet#29]
链接和密码都添了

**Comment by qinlili23333** [comment]
提供下链接

**Comment by igstranger** [comment]
> 提供下链接

https://url19.ctfile.com/d/21834319-47208498-94a1d5?p=1584
1584

可以看看这个，我也是打不开

**Comment by sdw81219** [comment]
https://url53.ctfile.com/d/1538653-47684988-b5de56 
123456
感谢

**Comment by qinlili23333** [comment]
文件夹解析不受支持，目前也没有计划支持
