### ISSUE TITLE
解析失败，文件不存在或密码错误

### ISSUE THREAD

**Issue by Ceyase** [qinlili23333/ctfileGet#3]
在我的网站测试您的API的时候哦发现一个问题
https://url21.ctfile.com/f/35031121-532806680-924b31 （访问密码：6290）
这个文件使用index.html进行解析时可以正常解析，但当使用redirect.html的时候便会报错
解析失败，文件不存在或密码错误
使用链接：https://ctfile.qinlili.bid/redirect.html?file=35031121-532806680-924b31?pass=6290
请问是我的使用问题还是程序问题？

**Comment by Ceyase** [comment]
我傻了，Get请求我为啥写两个?，抱歉了

**Comment by qinlili23333** [comment]
绷不住了这下
