### ISSUE TITLE
https://ctfile.qinlili.bid解析出错

### ISSUE THREAD

**Issue by singowang** [qinlili23333/ctfileGet#4]
你好：

文件地址：https://306t.com/file/133802-295793064

复制133802-295793064或者上面整个网址 到  分享链接就框内提示：

出错了，错误原因是:分享链接打开不完整。

不知道是我使用的方式不对还是怎样，希望此反馈对你有帮助。

**Comment by qinlili23333** [comment]
此类旧格式地址请使用船新按钮版（页面顶端切换），并使用文件id而不是完整链接

**Comment by qinlili23333** [comment]
暂不支持此类旧格式地址的解析，请联系分享者获取新格式地址

**Comment by singowang** [comment]
> 暂不支持此类旧格式地址的解析，请联系分享者获取新格式地址

好的，谢谢你的回复！
