### ISSUE TITLE
关于解析出的下载地址

### ISSUE THREAD

**Issue by songgedodo** [qinlili23333/ctfileGet#5]
请问为什么请求get_file_url.php这个接口，有时候解析出来的是93-cucc-dd.tv002.com开头的正常下载链接，有时候是88-cucc-dd.tv002.com/101.69.122.88:443，而不是正常的下载链接

**Comment by songgedodo** [comment]
似乎和网络环境有关，换成移动网络请求就没关系，想请教一下原因

**Comment by lanjerry** [comment]
@qinlili23333 老板，我打开了，显示分享链接打开不完整。比如 http://26dn.56suu.tak856.rth22.3dmxz.com/file/16872857-241438280

**Comment by qinlili23333** [comment]
> @qinlili23333 老板，我打开了，显示分享链接打开不完整。比如 http://26dn.56suu.tak856.rth22.3dmxz.com/file/16872857-241438280

你使用的分享地址是20年以前的旧的格式，请重新生成新的分享地址

**Comment by songgedodo** [comment]
感谢

**Comment by songgedodo** [comment]
感谢
