### ISSUE TITLE
报错：免费用户仅可同时下载一个文件

### ISSUE THREAD

**Issue by Ceyase** [qinlili23333/ctfileGet#9]
如题，不过我使用的是Workers版本，当两个或以上的人同时使用一个API将会出这个错。

**Comment by qinlili23333** [comment]
这是城通网盘自身的限制

**Comment by Ceyase** [comment]
那请问怎么搞呢，总不能我自己买个会员然后用token解析吧

**Comment by qinlili23333** [comment]
> 那请问怎么搞呢，总不能我自己买个会员然后用token解析吧

这是可行办法之一，另一个办法是八用户分散到不同的cloudflare数据中心（需要cf企业版）
